/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ali Rahimi (https://sketchfab.com/Free-Radical-666)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/titan-646952b9348443c0892672204ab3779c
Title: Titan
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Titan(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/titan.glb')
    const { actions } = useAnimations(animations, group)
    useEffect(()=>{
      if(animations.length > 0){
          actions[animations[0].name]?.play()
    }
  },[actions, animations])
  return (
    <group {...props} dispose={null}
        rotation={[Math.PI / 25, 200, 0]} 
        scale={0.263}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Head_A_Head_A__0.geometry}
        material={materials.Head_A}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Left_Hand__Left_Hand___0.geometry}
        material={materials.Left_Hand}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPipe1_Head_B__0.geometry}
        material={materials.Head_B}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.a11Mesh_Head_C__0.geometry}
        material={materials.Head_C}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.a9Mesh_Pillar_0.geometry}
        material={materials.Pillar}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fire_Fire__0.geometry}
        material={materials.Fire}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pSphere13_lambert1_0.geometry}
        material={materials.lambert1}
        position={[0, 46.498, 0]}
        scale={7.552}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder35_EYE_A__0.geometry}
        material={materials.EYE_A}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder35_EYE_B__0.geometry}
        material={materials.EYE_B}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder35_EYE_C__0.geometry}
        material={materials.EYE_C}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fire_HolderMesh_Fire_Holder__0.geometry}
        material={materials.Fire_Holder}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Right_Hand_Skf__Right_Hand___0.geometry}
        material={materials.Right_Hand}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Right_Hand_Skf__Right_Hand___0_1.geometry}
        material={materials.Right_Hand}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Right_Hand_Skf__Right_Hand___0_2.geometry}
        material={materials.Right_Hand}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube1_Boundry_0.geometry}
        material={materials.Boundry}
      />
    </group>
  )
}

useGLTF.preload('/models/titan.glb')